drop database if exists HavenGeek;
create database HavenGeek;
use HavenGeek;
 
      CREATE TABLE CLIENTE (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR2(200) NOT NULL,
        EMAIL VARCHAR2(100) NOT NULL,
        ENDERECO VARCHAR2(200),
        USERNAME VARCHAR2(20) NOT NULL,
        PRIMARY KEY (ID)
);

    CREATE TABLE ACESSORIO (
        ID INT NOT NULL AUTO_INCREMENT,
        DESCRICAO VARCHAR2(200) NOT NULL,
        PRECO DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (ID)
);		

    CREATE TABLE JOGO (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR2(200) NOT NULL,
        TIPO_MIDIA VARCHAR2(1) NOT NULL,
        PRECO DECIMAL(10,2) NOT NULL,
        CATEGORIA VARCHAR2(200) NOT NULL,
        PLATAFORMA VARCHAR2(20) NOT NULL,
        PRIMARY KEY (ID)
);

    CREATE TABLE CARRINHO (
        ID INT NOT NULL AUTO_INCREMENT,
        ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID),
        ID_JOGO INT REFERENCES JOGO(ID),
        ID_ACESSORIO INT REFERENCES ACESSORIO(ID),
        PRIMARY KEY (ID) 
);

    CREATE TABLE VENDA (
        ID INT NOT NULL AUTO_INCREMENT,
        ID_CARRINHO INT NOT NULL REFERENCES CARRINHO(ID),
        PRIMARY KEY (ID)
);
