drop database if exists HavenGeek;
create database HavenGeek;
use HavenGeek;
 
      CREATE TABLE CLIENTE (
        ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR2(200) NOT NULL,
        EMAIL VARCHAR2(100) NOT NULL,
        ENDERECO VARCHAR2(200),
        USERNAME VARCHAR2(20) NOT NULL,
        PRIMARY KEY (ID_CLIENTE)
);

    CREATE TABLE ACESSORIO (
        ID_ACESSORIO INT NOT NULL AUTO_INCREMENT,
        DESCRICAO VARCHAR2(200) NOT NULL,
        PRECO DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (ID_ACESSORIO)
);

    CREATE TABLE JOGO (
        ID_JOGO INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR2(200) NOT NULL,
        TIPO_MIDIA VARCHAR2(1) NOT NULL,
        PRECO DECIMAL(10,2) NOT NULL,
        CATEGORIA VARCHAR2(200) NOT NULL,
        PLATAFORMA VARCHAR2(20) NOT NULL,
        PRIMARY KEY (ID_JOGO)
);

    CREATE TABLE CARRINHO (
        ID_CARRINHO INT NOT NULL AUTO_INCREMENT,
        ID_CLIENTE INT NOT NULL REFERENCES CLIENTE(ID_CLIENTE),
        ID_JOGO INT NOT NULL REFERENCES JOGO(ID_JOGO),
        ID_ACESSORIO INT NOT NULL REFERENCES ACESSORIO(ID_ACESSORIO),
        PRIMARY KEY (ID_CARRINHO) 
);

    CREATE TABLE VENDA (
        ID_VENDA INT NOT NULL AUTO_INCREMENT,
        ID_CARRINHO INT NOT NULL REFERENCES CARRINHO(ID_CARRINHO),
        PRIMARY KEY (ID_VENDA)
);
